import { getCurrentLanguage } from '../../utils/translations';

const en = {
  lang: 'en',
  phaseLabels: {
    waiting: 'WAITING',
    gameOver: 'GAME OVER',
    roundOver: 'ROUND OVER',
    drawing: 'DRAWING',
    playingCard: 'PLAYING CARD',
    draw: 'DRAW',
    play: 'PLAY',
  },
  settings: {
    title: 'Settings',
    subcopy: 'Fixed layout for Prime Suspect.',
    room: 'Room',
    feed: 'Feed',
    code: 'Code',
    phase: 'Phase',
    players: 'Players',
    cameras: 'Cameras',
    mode: 'Mode',
    streamer: 'Streamer',
    roomMode: 'Room',
    namesBelowVideo: 'Names below video',
    showRoomCode: 'Show room code',
    showChatTicker: 'Show chat ticker',
    lockForCapture: 'Lock for capture',
    closeWindow: 'Close window',
    obsHint: 'Crop the thin right edge in OBS if you want the unlock strip hidden after locking.',
  },
  content: {
    windowTitle: 'Broadcast',
    waitingForGameToStart: 'Waiting for game to start',
    roundPrefix: 'ROUND',
    winnerTakesRound: '{name} wins the round!',
    roundOver: 'Round over',
    drawingTurn: '{name} - Drawing...',
    playingTurn: '{name} - Playing...',
    solvedCase: '{name} solved the case!',
    gameOver: 'Game over',
    openBroadcastControls: 'Open broadcast controls',
    unlock: 'Unlock',
  },
  stage: {
    waitingForPlayers: 'Waiting for players...',
    playersInLobby: '{count} player{s} in lobby',
    winsRoundBanner: '{name} wins Round {round}!',
    drawPhase: 'Draw Phase',
    playPhase: 'Play Phase',
    deck: 'Deck',
    cards: 'cards',
    faceUp: 'Face Up',
    tokenStandings: 'Token Standings - First to {count}',
    playersRace: 'Players - First to {count} tokens',
    out: 'Out',
    immune: 'Immune',
    recentPlays: 'Recent Plays',
    forced: 'Forced',
    played: 'Played',
    caseSolved: 'Case Solved!',
    rounds: 'Rounds',
    players: 'Players',
    tokens: 'Tokens',
    finalStandings: 'Final Standings',
    tokenUnit: 'tokens',
    unknown: 'Unknown',
  },
  cardNames: {
    1: 'Inspector',
    2: 'Butler',
    3: 'Witness',
    4: 'Lawyer',
    5: 'Blackmailer',
    6: 'Double Agent',
    7: 'Accomplice',
    8: 'Murderer',
  },
  controls: {
    joinVideoChat: 'Join video chat',
    joinVideo: 'Join Video',
    settingUp: 'Setting up...',
    collapseVideos: 'Collapse videos',
    expandVideos: 'Expand videos',
    videos: 'Videos',
    turnOffCamera: 'Turn off camera',
    turnOnCamera: 'Turn on camera',
    muteMicrophone: 'Mute microphone',
    unmuteMicrophone: 'Unmute microphone',
    videoSettings: 'Video settings',
    leaveVideoChat: 'Leave video chat',
    openBroadcastWindow: 'Open broadcast window (B)',
  },
  mobileGrid: {
    you: 'You',
    more: 'more',
  },
  deviceSettings: {
    devices: 'Devices',
    background: 'Background',
    audio: 'Audio',
    avatar: 'Avatar',
    cameraSetup: 'Camera Setup',
    cameraSettings: 'Camera Settings',
    joinVideoChat: 'Join Video Chat',
    videoSettings: 'Video Settings',
    cameraOff: 'Camera Off',
    loadingVirtualBackground: 'Loading virtual background...',
    virtualBackgroundActive: 'Virtual BG Active',
    camera: 'Camera',
    microphone: 'Microphone',
    noCamerasFound: 'No cameras found',
    noMicrophonesFound: 'No microphones found',
    audioLevel: 'Audio Level',
    joinMuted: 'Join Muted',
    joinWithCameraOff: 'Join with Camera Off',
    virtualBackgroundBrowserSupport: 'Virtual backgrounds require Chrome 108+ or a browser with Insertable Streams support.',
    enableVirtualBackground: 'Enable Virtual Background',
    blur: 'Blur',
    virtualBackgroundInfo: 'Virtual backgrounds use AI-powered segmentation to replace your background in real-time.',
    noiseSuppression: 'AI Noise Suppression',
    noiseThreshold: 'Noise Threshold',
    sensitive: 'Sensitive',
    aggressive: 'Aggressive',
    noiseSuppressionInfo: 'Reduces background noise like keyboard clicks, fans, and ambient sounds during video chat.',
    faceAvatar: '3D Face Avatar',
    raccoon: 'Raccoon',
    robot: 'Robot',
    alien: 'Alien',
    cat: 'Cat',
    soon: 'Soon',
    avatarInfo: 'Your face movements control a 3D avatar using AI-powered face tracking. Your real face is never shown.',
    cancel: 'Cancel',
    close: 'Close',
    saveSettings: 'Save Settings',
  },
};

const de: typeof en = {
  lang: 'de',
  phaseLabels: {
    waiting: 'WARTEN',
    gameOver: 'SPIELENDE',
    roundOver: 'RUNDENENDE',
    drawing: 'ZIEHEN',
    playingCard: 'KARTE SPIELEN',
    draw: 'ZIEHEN',
    play: 'SPIELEN',
  },
  settings: {
    title: 'Einstellungen',
    subcopy: 'Festes Layout fuer Prime Suspect.',
    room: 'Raum',
    feed: 'Feed',
    code: 'Code',
    phase: 'Phase',
    players: 'Spieler',
    cameras: 'Kameras',
    mode: 'Modus',
    streamer: 'Streamer',
    roomMode: 'Raum',
    namesBelowVideo: 'Namen unter dem Video',
    showRoomCode: 'Raumcode zeigen',
    showChatTicker: 'Chat-Ticker zeigen',
    lockForCapture: 'Fuer Capture sperren',
    closeWindow: 'Fenster schliessen',
    obsHint: 'Schneide den schmalen rechten Rand in OBS weg, wenn der Entsperr-Streifen nach dem Sperren verborgen sein soll.',
  },
  content: {
    windowTitle: 'Broadcast',
    waitingForGameToStart: 'Warte auf den Spielstart',
    roundPrefix: 'RUNDE',
    winnerTakesRound: '{name} gewinnt die Runde!',
    roundOver: 'Runde beendet',
    drawingTurn: '{name} - Zieht...',
    playingTurn: '{name} - Spielt...',
    solvedCase: '{name} hat den Fall geloest!',
    gameOver: 'Spiel beendet',
    openBroadcastControls: 'Broadcast-Steuerung oeffnen',
    unlock: 'Entsperren',
  },
  stage: {
    waitingForPlayers: 'Warte auf Spieler...',
    playersInLobby: '{count} Spieler im Raum',
    winsRoundBanner: '{name} gewinnt Runde {round}!',
    drawPhase: 'Ziehphase',
    playPhase: 'Spielphase',
    deck: 'Stapel',
    cards: 'Karten',
    faceUp: 'Offen',
    tokenStandings: 'Tokenstand - Zuerst auf {count}',
    playersRace: 'Spieler - Zuerst auf {count} Token',
    out: 'Raus',
    immune: 'Immun',
    recentPlays: 'Letzte Zuege',
    forced: 'Erzwungen',
    played: 'Gespielt',
    caseSolved: 'Fall geloest!',
    rounds: 'Runden',
    players: 'Spieler',
    tokens: 'Token',
    finalStandings: 'Endstand',
    tokenUnit: 'Token',
    unknown: 'Unbekannt',
  },
  cardNames: {
    1: 'Inspektor',
    2: 'Butler',
    3: 'Zeuge',
    4: 'Anwalt',
    5: 'Erpresser',
    6: 'Doppelagent',
    7: 'Komplize',
    8: 'Moerder',
  },
  controls: {
    joinVideoChat: 'Videochat beitreten',
    joinVideo: 'Video beitreten',
    settingUp: 'Wird eingerichtet...',
    collapseVideos: 'Videos einklappen',
    expandVideos: 'Videos ausklappen',
    videos: 'Videos',
    turnOffCamera: 'Kamera ausschalten',
    turnOnCamera: 'Kamera einschalten',
    muteMicrophone: 'Mikrofon stummschalten',
    unmuteMicrophone: 'Mikrofon einschalten',
    videoSettings: 'Videoeinstellungen',
    leaveVideoChat: 'Videochat verlassen',
    openBroadcastWindow: 'Broadcast-Fenster oeffnen (B)',
  },
  mobileGrid: {
    you: 'Du',
    more: 'mehr',
  },
  deviceSettings: {
    devices: 'Geraete',
    background: 'Hintergrund',
    audio: 'Audio',
    avatar: 'Avatar',
    cameraSetup: 'Kamera einrichten',
    cameraSettings: 'Kameraeinstellungen',
    joinVideoChat: 'Videochat beitreten',
    videoSettings: 'Videoeinstellungen',
    cameraOff: 'Kamera aus',
    loadingVirtualBackground: 'Virtueller Hintergrund wird geladen...',
    virtualBackgroundActive: 'Virtueller Hintergrund aktiv',
    camera: 'Kamera',
    microphone: 'Mikrofon',
    noCamerasFound: 'Keine Kameras gefunden',
    noMicrophonesFound: 'Keine Mikrofone gefunden',
    audioLevel: 'Audiopegel',
    joinMuted: 'Stumm beitreten',
    joinWithCameraOff: 'Mit ausgeschalteter Kamera beitreten',
    virtualBackgroundBrowserSupport: 'Virtuelle Hintergruende benoetigen Chrome 108+ oder einen Browser mit Insertable-Streams-Unterstuetzung.',
    enableVirtualBackground: 'Virtuellen Hintergrund aktivieren',
    blur: 'Weichzeichnen',
    virtualBackgroundInfo: 'Virtuelle Hintergruende nutzen KI-Segmentierung, um deinen Hintergrund in Echtzeit zu ersetzen.',
    noiseSuppression: 'KI-Geraeuschunterdrueckung',
    noiseThreshold: 'Geraeuschschwelle',
    sensitive: 'Empfindlich',
    aggressive: 'Stark',
    noiseSuppressionInfo: 'Reduziert Hintergrundgeraeusche wie Tastaturklicks, Luefter und Umgebungslaerm im Videochat.',
    faceAvatar: '3D-Gesichtsavatar',
    raccoon: 'Waschbaer',
    robot: 'Roboter',
    alien: 'Alien',
    cat: 'Katze',
    soon: 'Bald',
    avatarInfo: 'Deine Gesichtsbewegungen steuern einen 3D-Avatar per KI-Gesichtstracking. Dein echtes Gesicht wird nie gezeigt.',
    cancel: 'Abbrechen',
    close: 'Schliessen',
    saveSettings: 'Einstellungen speichern',
  },
};

const es: typeof en = {
  lang: 'es',
  phaseLabels: {
    waiting: 'ESPERANDO',
    gameOver: 'FIN DEL JUEGO',
    roundOver: 'FIN DE RONDA',
    drawing: 'ROBANDO',
    playingCard: 'JUGANDO CARTA',
    draw: 'ROBAR',
    play: 'JUGAR',
  },
  settings: {
    title: 'Configuracion',
    subcopy: 'Diseno fijo para Prime Suspect.',
    room: 'Sala',
    feed: 'Feed',
    code: 'Codigo',
    phase: 'Fase',
    players: 'Jugadores',
    cameras: 'Camaras',
    mode: 'Modo',
    streamer: 'Streamer',
    roomMode: 'Sala',
    namesBelowVideo: 'Nombres bajo el video',
    showRoomCode: 'Mostrar codigo de sala',
    showChatTicker: 'Mostrar ticker de chat',
    lockForCapture: 'Bloquear para captura',
    closeWindow: 'Cerrar ventana',
    obsHint: 'Recorta el borde derecho en OBS si quieres ocultar la franja de desbloqueo despues de bloquear.',
  },
  content: {
    windowTitle: 'Broadcast',
    waitingForGameToStart: 'Esperando que comience el juego',
    roundPrefix: 'RONDA',
    winnerTakesRound: '{name} gana la ronda!',
    roundOver: 'Ronda terminada',
    drawingTurn: '{name} - Robando...',
    playingTurn: '{name} - Jugando...',
    solvedCase: '{name} resolvio el caso!',
    gameOver: 'Fin del juego',
    openBroadcastControls: 'Abrir controles de transmision',
    unlock: 'Desbloquear',
  },
  stage: {
    waitingForPlayers: 'Esperando jugadores...',
    playersInLobby: '{count} jugador{s} en la sala',
    winsRoundBanner: '{name} gana la Ronda {round}!',
    drawPhase: 'Fase de robo',
    playPhase: 'Fase de juego',
    deck: 'Mazo',
    cards: 'cartas',
    faceUp: 'Boca arriba',
    tokenStandings: 'Puntuacion - Primero en {count}',
    playersRace: 'Jugadores - Primero en {count} fichas',
    out: 'Fuera',
    immune: 'Inmune',
    recentPlays: 'Jugadas recientes',
    forced: 'Forzado',
    played: 'Jugado',
    caseSolved: 'Caso resuelto!',
    rounds: 'Rondas',
    players: 'Jugadores',
    tokens: 'Fichas',
    finalStandings: 'Clasificacion final',
    tokenUnit: 'fichas',
    unknown: 'Desconocido',
  },
  cardNames: {
    1: 'Inspector',
    2: 'Mayordomo',
    3: 'Testigo',
    4: 'Abogado',
    5: 'Chantajista',
    6: 'Agente doble',
    7: 'Complice',
    8: 'Asesino',
  },
  controls: {
    joinVideoChat: 'Unirse al video chat',
    joinVideo: 'Unirse al video',
    settingUp: 'Configurando...',
    collapseVideos: 'Contraer videos',
    expandVideos: 'Expandir videos',
    videos: 'Videos',
    turnOffCamera: 'Apagar camara',
    turnOnCamera: 'Encender camara',
    muteMicrophone: 'Silenciar microfono',
    unmuteMicrophone: 'Activar microfono',
    videoSettings: 'Configuracion de video',
    leaveVideoChat: 'Salir del video chat',
    openBroadcastWindow: 'Abrir ventana de transmision (B)',
  },
  mobileGrid: {
    you: 'Tu',
    more: 'mas',
  },
  deviceSettings: {
    devices: 'Dispositivos',
    background: 'Fondo',
    audio: 'Audio',
    avatar: 'Avatar',
    cameraSetup: 'Configuracion de camara',
    cameraSettings: 'Ajustes de camara',
    joinVideoChat: 'Unirse al video chat',
    videoSettings: 'Configuracion de video',
    cameraOff: 'Camara apagada',
    loadingVirtualBackground: 'Cargando fondo virtual...',
    virtualBackgroundActive: 'Fondo virtual activo',
    camera: 'Camara',
    microphone: 'Microfono',
    noCamerasFound: 'No se encontraron camaras',
    noMicrophonesFound: 'No se encontraron microfonos',
    audioLevel: 'Nivel de audio',
    joinMuted: 'Unirse silenciado',
    joinWithCameraOff: 'Unirse con camara apagada',
    virtualBackgroundBrowserSupport: 'Los fondos virtuales requieren Chrome 108+ o un navegador con soporte de Insertable Streams.',
    enableVirtualBackground: 'Activar fondo virtual',
    blur: 'Desenfocar',
    virtualBackgroundInfo: 'Los fondos virtuales usan segmentacion por IA para reemplazar tu fondo en tiempo real.',
    noiseSuppression: 'Supresion de ruido IA',
    noiseThreshold: 'Umbral de ruido',
    sensitive: 'Sensible',
    aggressive: 'Agresivo',
    noiseSuppressionInfo: 'Reduce el ruido de fondo como teclas, ventiladores y sonidos ambientales durante el video chat.',
    faceAvatar: 'Avatar facial 3D',
    raccoon: 'Mapache',
    robot: 'Robot',
    alien: 'Alien',
    cat: 'Gato',
    soon: 'Pronto',
    avatarInfo: 'Tus movimientos faciales controlan un avatar 3D usando seguimiento facial por IA. Tu rostro real nunca se muestra.',
    cancel: 'Cancelar',
    close: 'Cerrar',
    saveSettings: 'Guardar configuracion',
  },
};

export function getBroadcastCopy() {
  const lang = getCurrentLanguage();
  if (lang === 'de') return de;
  if (lang === 'es') return es;
  return en;
}
