import { getCurrentLanguage } from '../../utils/translations';

const en = {
  phaseLabels: {
    lobby: 'WAITING',
    questionDisplay: 'QUESTION',
    lieInput: 'WRITE BLUFF',
    voting: 'VOTING',
    reveal: 'REVEAL',
    scores: 'SCORES',
    gameOver: 'GAME OVER',
  },
  settings: {
    title: 'Settings',
    subcopy: 'Fixed layout for Prime Suspect.',
    room: 'Room',
    feed: 'Feed',
    code: 'Code',
    phase: 'Phase',
    players: 'Players',
    cameras: 'Cameras',
    mode: 'Mode',
    streamer: 'Streamer',
    roomMode: 'Room',
    namesBelowVideo: 'Names below video',
    showRoomCode: 'Show room code',
    showChatTicker: 'Show chat ticker',
    lockForCapture: 'Lock for capture',
    closeWindow: 'Close window',
    obsHint: 'Crop the thin right edge in OBS if you want the unlock strip hidden after locking.',
  },
  content: {
    windowTitle: 'Broadcast',
    previewLabel: 'Preview',
    waitingForGameToStart: 'Waiting for game to start',
    roundLabel: 'Round',
    questionInProgress: 'Question revealed',
    writingBluffs: 'Players writing bluffs',
    bluffsSubmitted: '{submitted}/{total} bluffs submitted',
    votingLive: 'Voting in progress',
    revealAnswers: 'Revealing answers',
    scoresUpdate: 'Round scores',
    gameOver: 'Game over',
    go: 'GO!',
    openBroadcastControls: 'Open broadcast controls',
    unlock: 'Unlock',
    votesIn: '{voted}/{total} votes in',
    correctAnswerLabel: 'Correct answer',
    votesSuffix: 'votes',
    leaderboardTitle: 'Standings',
    winnerLabel: 'Winner',
  },
  controls: {
    openBroadcastWindow: 'Open broadcast window (B)',
  },
};

const de: typeof en = {
  phaseLabels: {
    lobby: 'WARTEN',
    questionDisplay: 'FRAGE',
    lieInput: 'BLUFF SCHREIBEN',
    voting: 'ABSTIMMUNG',
    reveal: 'ENTHÜLLUNG',
    scores: 'PUNKTE',
    gameOver: 'SPIELENDE',
  },
  settings: {
    title: 'Einstellungen',
    subcopy: 'Festes Layout für Prime Suspect.',
    room: 'Raum',
    feed: 'Feed',
    code: 'Code',
    phase: 'Phase',
    players: 'Spieler',
    cameras: 'Kameras',
    mode: 'Modus',
    streamer: 'Streamer',
    roomMode: 'Raum',
    namesBelowVideo: 'Namen unter dem Video',
    showRoomCode: 'Raumcode zeigen',
    showChatTicker: 'Chat-Ticker zeigen',
    lockForCapture: 'Für Capture sperren',
    closeWindow: 'Fenster schließen',
    obsHint: 'Schneide den schmalen rechten Rand in OBS weg, wenn der Entsperr-Streifen nach dem Sperren verborgen sein soll.',
  },
  content: {
    windowTitle: 'Broadcast',
    previewLabel: 'Vorschau',
    waitingForGameToStart: 'Warte auf den Spielstart',
    roundLabel: 'Runde',
    questionInProgress: 'Frage enthüllt',
    writingBluffs: 'Spieler schreiben Bluffs',
    bluffsSubmitted: '{submitted}/{total} Bluffs eingereicht',
    votingLive: 'Abstimmung läuft',
    revealAnswers: 'Antworten werden enthüllt',
    scoresUpdate: 'Rundenpunkte',
    gameOver: 'Spiel beendet',
    go: 'LOS!',
    openBroadcastControls: 'Broadcast-Steuerung öffnen',
    unlock: 'Entsperren',
    votesIn: '{voted}/{total} Stimmen abgegeben',
    correctAnswerLabel: 'Richtige Antwort',
    votesSuffix: 'Stimmen',
    leaderboardTitle: 'Punktestand',
    winnerLabel: 'Gewinner',
  },
  controls: {
    openBroadcastWindow: 'Broadcast-Fenster öffnen (B)',
  },
};

export function getBroadcastCopy() {
  return getCurrentLanguage() === 'de' ? de : en;
}
